language: node_js
node_js: 6
dist: trusty
sudo: required
env:
  global:
    - CC_TEST_REPORTER_ID=6bacc51343b3849f547babc6eda6aa0df0a1dd06056be0fc0324319d3028d5f9
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  yarn: true
  directories:
    - node_modules
    - bower_components
    - bower_components-1.x
    - ".eslintcache"
    - "$HOME/.cache/bower"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - yarn run lint
script:
  - xvfb-run yarn test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  slack:
    secure: wUdQ7WsRenhKaMtGiNwzvZQHpxdkLe6agFfjIh7iCosrcxhbBpIrE2hB830hKu4TNREvLzKyx+36QcJjWiSjm/yiSFLkTTNL1z6ZmG5x5EOkuB6CF7aD8sGJ6qvfVMSFq4aKF7tVxixhhIDT5ZkynNaHDcATdaWdyU5EB/kJSg1TBIbaXzpi3+tBqpxXKWX3bAl6X0vTSVxeMEhrWEVOZyNPuC2kaY7D8odbQ1jjTO+SmCLefoEt8GjgLjlzXdE7rlRn3NB+ojnW0Zgcbh8tnKvOKyRernZRCBNlr/ohzIixM84NhUqaNyha1sSKQM8zaeMPqQ7taWCO/dhKDuJuvQS+c+4zOoHfsme1eh3HqYxmdlCZcZf26eRCCS0Ce4L/+8gj5ncoWJuiXSFr33yK9tiu3kNK7CjEzabJD7GMHyjqsmlfVeKMG9pgJUyHUanTjz//CA1c7zyAqf8xHiW789Lnm9q/+2RHl7+rEu9OJOwMnmW9m53qfvAZB02SWanb/OKMK+0XbzCJmCk601dmILWARgoovibxDOd2JxG4ATN5dLCrPhYj5o/0Mv0LO8GeeaAntfoogfu5tsX9Jqtp2Fvn+ejpNrNzty5CEQPSByGdcfQRTx7EyQyYcVFGy3dGZbMnD7hEHfAzddVl2S8m1GDO0RVE8gj+CYt0Cvcq228=
